import json
import re

from fastapi import HTTPException
from pydantic import ValidationError

from app.core.config import get_settings
from app.models.analysis import (
    AnalysisResponse,
    AnalyzeRequest,
    CrossQuestion,
    DayPlan,
    DebugInfo,
    InterviewQuestion,
    MatchingSkill,
    MissingSkill,
    ResumeImprovement,
    SystemDesignReadiness,
    WeaklyEvidencedSkill,
)
from app.services.llm_client import call_llm
from app.services.preparation_service import build_preparation_intelligence
from app.services.prompt_builder import build_analysis_prompt
from app.services.scoring_service import score_resume_against_jd


def analyze_resume_jd(request: AnalyzeRequest) -> AnalysisResponse:
    mode, _provider, _model = _resolve_llm_options(request)
    if mode == "mock":
        return _analyze_with_mock(request)

    return _analyze_with_llm(request)


def _analyze_with_llm(request: AnalyzeRequest) -> AnalysisResponse:
    settings = get_settings()
    _mode, provider, model = _resolve_llm_options(request)
    prompt = build_analysis_prompt(request)
    raw_response = call_llm(prompt, settings, provider=provider, model=model)
    parsed = _parse_json_response(raw_response)

    try:
        response = AnalysisResponse.model_validate(parsed)
    except ValidationError as exc:
        raise HTTPException(status_code=502, detail=f"AI response schema validation failed: {exc}") from exc

    _attach_algorithmic_scoring(response, request)
    _ensure_plan_length(response, request.preparationPlanDays)
    response.debug = DebugInfo(
        mode="llm",
        provider=provider,
        model=model,
        promptPreview=prompt[:1800],
        receivedExperienceYears=request.candidateContext.experienceYears,
        receivedTargetRole=request.candidateContext.targetRole,
        receivedCurrentStack=request.candidateContext.currentStack,
        scoreReason=(
            f"Live coaching content generated by {provider} model {model}. "
            "Numeric scoring is calculated by the explainable Level 1.5/2 scoring engine."
        ),
    )
    return response


def _parse_json_response(raw_response: str) -> dict:
    cleaned = raw_response.strip()
    fence_match = re.search(r"```(?:json)?\s*(.*?)```", cleaned, flags=re.DOTALL)
    if fence_match:
        cleaned = fence_match.group(1).strip()

    try:
        return json.loads(cleaned)
    except json.JSONDecodeError as exc:
        raise HTTPException(status_code=502, detail="AI returned invalid JSON") from exc


def _analyze_with_mock(request: AnalyzeRequest) -> AnalysisResponse:
    # Level 1 uses a deterministic mock so API/UI integration can be tested first.
    # The prompt is still built now to keep the real LLM boundary ready.
    prompt = build_analysis_prompt(request)
    _mode, provider, model = _resolve_llm_options(request)
    context = request.candidateContext
    scoring = score_resume_against_jd(request)
    score = scoring.technical_match_score
    fit_category = _fit_category(score)
    experience_label = f"{context.experienceYears} year" if context.experienceYears == 1 else f"{context.experienceYears} years"
    stack_label = ", ".join(context.currentStack)

    return AnalysisResponse(
        technicalMatchScore=score,
        overallSummary=(
            f"This mock analysis used the submitted context: {experience_label} of experience, "
            f"targeting {context.targetRole}, with current stack {stack_label}. The numeric score, "
            "requirement matches, gaps, and resume suggestions are generated from dynamically extracted "
            "JD requirements rather than a fixed skill list."
        ),
        fitCategory=fit_category,
        matchingSkills=_mock_matching_skills(scoring.requirement_matches),
        weaklyEvidencedSkills=_mock_weakly_evidenced_skills(scoring.requirement_matches),
        missingSkills=_mock_missing_skills(scoring.requirement_matches),
        resumeImprovements=_mock_resume_improvements(scoring.requirement_matches),
        interviewQuestions=_mock_interview_questions(scoring.requirement_matches),
        crossQuestions=_mock_cross_questions(scoring.requirement_matches),
        systemDesignReadiness=_mock_system_design_readiness(scoring.requirement_matches),
        sevenDayPlan=_build_preparation_plan(request.preparationPlanDays),
        debug=DebugInfo(
            mode="mock",
            provider=provider,
            model=model,
            promptPreview=prompt[:1800],
            receivedExperienceYears=context.experienceYears,
            receivedTargetRole=context.targetRole,
            receivedCurrentStack=context.currentStack,
            scoreReason=_score_reason(context.experienceYears, score),
        ),
        scoreBreakdown=scoring.score_breakdown,
        shortlistingScore=scoring.shortlisting_score,
        interviewReadinessScore=scoring.interview_readiness_score,
        overallOpportunityScore=scoring.overall_opportunity_score,
        shortlistingFactors=scoring.shortlisting_factors,
        requirementMatches=scoring.requirement_matches,
        recommendedAction=scoring.recommended_action,
        preparationIntelligence=build_preparation_intelligence(
            request,
            scoring.requirement_matches,
            scoring.score_breakdown,
        ),
    )


def _mock_matching_skills(matches) -> list[MatchingSkill]:
    strong = [match for match in matches if match.score >= 55 and match.bestEvidence]
    if not strong:
        return [
            MatchingSkill(
                skill="Dynamic JD fit",
                evidenceFromResume="No strong requirement-level evidence was found yet.",
                jdRequirement="Review the extracted requirement matrix for missing or weak evidence.",
            )
        ]
    return [
        MatchingSkill(
            skill=match.requirement,
            evidenceFromResume=match.bestEvidence or "Resume evidence not available.",
            jdRequirement=match.requirement,
        )
        for match in strong[:6]
    ]


def _mock_weakly_evidenced_skills(matches) -> list[WeaklyEvidencedSkill]:
    weak = [match for match in matches if 20 <= match.score < 55]
    if not weak:
        return [
            WeaklyEvidencedSkill(
                skill="Requirement evidence depth",
                source="The current dynamic matrix did not find many weak matches.",
                whyWeak="This can mean the resume either matches clearly or the JD has few extractable requirements.",
                howToStrengthenResume="Check the requirement matrix and add specific project bullets for any requirement that feels important.",
            )
        ]
    return [
        WeaklyEvidencedSkill(
            skill=match.requirement,
            source=match.bestEvidence or "Weak or indirect resume evidence.",
            whyWeak=match.reason,
            howToStrengthenResume=f"Add a concrete project, responsibility, or measurable result that proves: {match.requirement}.",
        )
        for match in weak[:5]
    ]


def _mock_missing_skills(matches) -> list[MissingSkill]:
    missing = [match for match in matches if match.score < 20]
    if not missing:
        return [
            MissingSkill(
                skill="No major missing dynamic requirement detected",
                importance="low",
                whyItMatters="The current requirement matrix did not find a hard missing requirement.",
                howToPrepare="Use the weak evidence and interview questions sections to strengthen proof depth.",
            )
        ]
    return [
        MissingSkill(
            skill=match.requirement,
            importance=match.importance,
            whyItMatters="This requirement was extracted from the JD but not proven strongly in the resume.",
            howToPrepare=f"Prepare the concept and add truthful resume evidence for: {match.requirement}.",
        )
        for match in missing[:6]
    ]


def _mock_resume_improvements(matches) -> list[ResumeImprovement]:
    weak_or_missing = [match for match in matches if match.score < 55]
    if not weak_or_missing:
        return [
            ResumeImprovement(
                currentIssue="Resume evidence mostly aligns with the extracted JD requirements.",
                suggestedBullet="Add one measurable result to the most relevant project so the recruiter can see impact, not only responsibility.",
                reason="Strong matches still improve when backed by numbers, ownership, and outcome.",
            )
        ]
    return [
        ResumeImprovement(
            currentIssue=f"Weak or missing evidence for: {match.requirement}",
            suggestedBullet=f"Add a truthful bullet showing where you used or prepared {match.requirement}, including project context and outcome.",
            reason="The scorer found the JD requirement dynamically, but the resume did not prove it strongly enough.",
        )
        for match in weak_or_missing[:5]
    ]


def _mock_interview_questions(matches) -> list[InterviewQuestion]:
    topics = [match.requirement for match in matches[:8]] or ["the target role requirements"]
    return [
        InterviewQuestion(
            topic=topic,
            question=f"Explain your practical experience with {topic}.",
            difficulty="medium",
            expectedFocus="Give project context, your exact responsibility, tradeoffs, problems faced, and measurable outcome.",
        )
        for topic in topics[:8]
    ]


def _mock_cross_questions(matches) -> list[CrossQuestion]:
    topics = [match.requirement for match in matches[:8]] or ["the most important JD requirement"]
    return [
        CrossQuestion(
            question=f"Where exactly is {topic} proven in your resume?",
            whyAsked="Interviewers validate whether a claimed JD match is real hands-on experience or only keyword familiarity.",
            expectedAnswerHint="Point to one project or work item, explain your role, and describe the result or learning.",
        )
        for topic in topics[:8]
    ]


def _mock_system_design_readiness(matches) -> SystemDesignReadiness:
    strong_count = sum(1 for match in matches if match.score >= 55)
    total = max(len(matches), 1)
    ratio = strong_count / total
    if ratio >= 0.7:
        level = "strong"
    elif ratio >= 0.4:
        level = "moderate"
    else:
        level = "weak"
    weak_topics = [match.requirement for match in matches if match.score < 55]
    return SystemDesignReadiness(
        level=level,
        reason="Readiness is inferred from how many dynamically extracted JD requirements are supported by resume evidence.",
        topicsToPrepare=weak_topics[:6] or [match.requirement for match in matches[:6]] or ["Role-specific system design fundamentals"],
    )


def _attach_algorithmic_scoring(response: AnalysisResponse, request: AnalyzeRequest) -> None:
    scoring = score_resume_against_jd(request)
    response.technicalMatchScore = scoring.technical_match_score
    response.fitCategory = _fit_category(scoring.technical_match_score)
    response.scoreBreakdown = scoring.score_breakdown
    response.shortlistingScore = scoring.shortlisting_score
    response.interviewReadinessScore = scoring.interview_readiness_score
    response.overallOpportunityScore = scoring.overall_opportunity_score
    response.shortlistingFactors = scoring.shortlisting_factors
    response.requirementMatches = scoring.requirement_matches
    response.recommendedAction = scoring.recommended_action
    response.preparationIntelligence = build_preparation_intelligence(
        request,
        scoring.requirement_matches,
        scoring.score_breakdown,
    )


def _build_preparation_plan(days: int) -> list[DayPlan]:
    base_plan = [
        DayPlan(day=1, focus="Requirement evidence review", tasks=["Review the requirement matrix.", "Mark each weak or missing requirement as true experience, learning gap, or not applicable."]),
        DayPlan(day=2, focus="Resume proof rewrite", tasks=["Rewrite bullets for the top weak requirements.", "Add project context, ownership, tools used, and measurable outcome where truthful."]),
        DayPlan(day=3, focus="Core technical revision", tasks=["Revise the highest-importance missing requirement from the JD.", "Prepare one practical explanation and one tradeoff for that topic."]),
        DayPlan(day=4, focus="Project deep dive", tasks=["Prepare one end-to-end project story mapped to the JD.", "Cover requirement, design, implementation, testing, deployment, and result."]),
        DayPlan(day=5, focus="Operational depth", tasks=["Prepare debugging, monitoring, release, or support examples relevant to the JD.", "Write concise answers for failures, tradeoffs, and ownership."]),
        DayPlan(day=6, focus="System thinking", tasks=["Design a small system related to the target role.", "Cover APIs/interfaces, data flow, scaling, reliability, security, and observability."]),
        DayPlan(day=7, focus="Mock interview", tasks=["Answer dynamic cross-questions aloud.", "Update the resume based on weak answers and missing proof."]),
    ]
    extended_topics = [
        ("Weak requirement drill", ["Pick one weak requirement and prepare concept, implementation example, and interview explanation."]),
        ("Hands-on practice", ["Build or revise a small proof-of-work task around the most important missing requirement."]),
        ("Architecture and tradeoffs", ["Prepare tradeoffs, constraints, failure modes, and scaling considerations for the target role."]),
        ("Behavioral and HR screen", ["Prepare notice period, role switch reason, salary expectation, and project explanation answers."]),
        ("Final revision", ["Revisit weak topics, retake mock questions, and refine concise interview answers."]),
    ]

    plan = base_plan[: min(days, len(base_plan))]
    next_day = len(plan) + 1
    while len(plan) < days:
        focus, tasks = extended_topics[(next_day - len(base_plan) - 1) % len(extended_topics)]
        plan.append(DayPlan(day=next_day, focus=focus, tasks=tasks))
        next_day += 1
    return [item.model_copy(update={"day": index + 1}) for index, item in enumerate(plan)]


def _ensure_plan_length(response: AnalysisResponse, days: int) -> None:
    if len(response.sevenDayPlan) == days:
        return
    if len(response.sevenDayPlan) > days:
        response.sevenDayPlan = [
            item.model_copy(update={"day": index + 1})
            for index, item in enumerate(response.sevenDayPlan[:days])
        ]
        return

    generated_plan = _build_preparation_plan(days)
    existing = [
        item.model_copy(update={"day": index + 1})
        for index, item in enumerate(response.sevenDayPlan)
    ]
    response.sevenDayPlan = existing + generated_plan[len(existing) :]


def _resolve_llm_options(request: AnalyzeRequest) -> tuple[str, str, str]:
    settings = get_settings()
    if request.llmOptions:
        return request.llmOptions.mode, request.llmOptions.provider, request.llmOptions.model
    return settings.llm_mode, settings.llm_provider, settings.llm_model


def _calculate_mock_score(request: AnalyzeRequest) -> int:
    context = request.candidateContext
    resume_and_stack = f"{request.resumeText} {' '.join(context.currentStack)}".lower()
    jd_text = request.jobDescriptionText.lower()

    score = 34
    score += min(context.experienceYears * 7, 28)

    keyword_weights = {
        ".net": 5,
        "asp.net": 5,
        "web api": 5,
        "sql": 5,
        "react": 4,
        "azure": 4,
        "entity framework": 4,
        "linq": 3,
        "ci/cd": 3,
    }

    for keyword, weight in keyword_weights.items():
        if keyword in resume_and_stack:
            score += weight
        elif keyword in jd_text:
            score += 1

    return max(0, min(score, 100))


def _fit_category(score: int) -> str:
    if score >= 85:
        return "Strong Fit"
    if score >= 70:
        return "Good Fit"
    if score >= 50:
        return "Partial Fit"
    return "Weak Fit"


def _score_reason(experience_years: int, score: int) -> str:
    return (
        f"Score is calculated by the explainable scoring engine using experience-wise weights, "
        f"skill overlap, role relevance, database/backend depth, cloud/devops evidence, system design "
        f"signals, and shortlisting constraints. Experience supplied: {experience_years} year(s). "
        f"Current technical score: {score}."
    )
