import json
import re

from fastapi import HTTPException
from pydantic import ValidationError

from app.core.config import get_settings
from app.models.analysis import (
    AnalysisResponse,
    AnalyzeRequest,
    CrossQuestion,
    DayPlan,
    DebugInfo,
    InterviewQuestion,
    MatchingSkill,
    MissingSkill,
    ResumeImprovement,
    SystemDesignReadiness,
    WeaklyEvidencedSkill,
)
from app.services.llm_client import call_llm
from app.services.prompt_builder import build_analysis_prompt
from app.services.scoring_service import score_resume_against_jd


def analyze_resume_jd(request: AnalyzeRequest) -> AnalysisResponse:
    mode, _provider, _model = _resolve_llm_options(request)
    if mode == "mock":
        return _analyze_with_mock(request)

    return _analyze_with_llm(request)


def _analyze_with_llm(request: AnalyzeRequest) -> AnalysisResponse:
    settings = get_settings()
    _mode, provider, model = _resolve_llm_options(request)
    prompt = build_analysis_prompt(request)
    raw_response = call_llm(prompt, settings, provider=provider, model=model)
    parsed = _parse_json_response(raw_response)

    try:
        response = AnalysisResponse.model_validate(parsed)
    except ValidationError as exc:
        raise HTTPException(status_code=502, detail=f"AI response schema validation failed: {exc}") from exc

    _attach_algorithmic_scoring(response, request)
    _ensure_plan_length(response, request.preparationPlanDays)
    response.debug = DebugInfo(
        mode="llm",
        provider=provider,
        model=model,
        promptPreview=prompt[:1800],
        receivedExperienceYears=request.candidateContext.experienceYears,
        receivedTargetRole=request.candidateContext.targetRole,
        receivedCurrentStack=request.candidateContext.currentStack,
        scoreReason=(
            f"Live coaching content generated by {provider} model {model}. "
            "Numeric scoring is calculated by the explainable Level 1.5/2 scoring engine."
        ),
    )
    return response


def _parse_json_response(raw_response: str) -> dict:
    cleaned = raw_response.strip()
    fence_match = re.search(r"```(?:json)?\s*(.*?)```", cleaned, flags=re.DOTALL)
    if fence_match:
        cleaned = fence_match.group(1).strip()

    try:
        return json.loads(cleaned)
    except json.JSONDecodeError as exc:
        raise HTTPException(status_code=502, detail="AI returned invalid JSON") from exc


def _analyze_with_mock(request: AnalyzeRequest) -> AnalysisResponse:
    # Level 1 uses a deterministic mock so API/UI integration can be tested first.
    # The prompt is still built now to keep the real LLM boundary ready.
    prompt = build_analysis_prompt(request)
    _mode, provider, model = _resolve_llm_options(request)
    context = request.candidateContext
    scoring = score_resume_against_jd(request)
    score = scoring.technical_match_score
    fit_category = _fit_category(score)
    experience_label = f"{context.experienceYears} year" if context.experienceYears == 1 else f"{context.experienceYears} years"
    stack_label = ", ".join(context.currentStack)

    return AnalysisResponse(
        technicalMatchScore=score,
        overallSummary=(
            f"This mock analysis used the submitted context: {experience_label} of experience, "
            f"targeting {context.targetRole}, with current stack {stack_label}. The candidate has "
            "technical signals around backend API, SQL, frontend exposure, and delivery work. The "
            "main gaps remain clear evidence of cloud, CI/CD, ORM depth, and end-to-end ownership."
        ),
        fitCategory=fit_category,
        matchingSkills=[
            MatchingSkill(skill="Backend APIs", evidenceFromResume="Mentions ASP.NET Core APIs and API integration.", jdRequirement="ASP.NET, .NET Core, Web API."),
            MatchingSkill(skill="SQL", evidenceFromResume="Mentions SQL Server experience.", jdRequirement="SQL and enterprise application development."),
            MatchingSkill(skill="Frontend exposure", evidenceFromResume="Mentions React UI changes.", jdRequirement="HTML, CSS, JavaScript, jQuery frontend skills."),
            MatchingSkill(skill="Agile delivery", evidenceFromResume="Mentions Agile delivery and production support.", jdRequirement="Collaborative agile environment."),
            MatchingSkill(skill=".NET experience", evidenceFromResume=f"Candidate context says {experience_label}; resume text is still the primary evidence for actual project depth.", jdRequirement="2 to 5 years of ASP.NET, .NET Core, C# experience."),
        ],
        weaklyEvidencedSkills=[
            WeaklyEvidencedSkill(
                skill="Entity Framework",
                source="The resume mentions .NET APIs and SQL Server but not ORM usage.",
                whyWeak="The JD explicitly asks for Entity Framework, but the resume does not prove hands-on usage.",
                howToStrengthenResume="Add a bullet about EF Core models, LINQ queries, migrations, or repository/data access work if applicable.",
            ),
            WeaklyEvidencedSkill(
                skill="Azure DevOps CI/CD",
                source="The resume mentions Agile and production support but not pipeline ownership.",
                whyWeak="Production support does not automatically prove CI/CD pipeline experience.",
                howToStrengthenResume="Mention build/release pipelines, deployment steps, pull request checks, or Azure DevOps boards if used.",
            ),
        ],
        missingSkills=[
            MissingSkill(skill="Azure Cloud Services", importance="high", whyItMatters="The JD calls out Azure Cloud Services for Microsoft client projects.", howToPrepare="Learn App Service, Azure SQL, Key Vault, Storage, monitoring, and deployment basics."),
            MissingSkill(skill="LINQ", importance="high", whyItMatters="LINQ is a core .NET interview topic and appears directly in the JD.", howToPrepare="Practice filtering, projection, grouping, joins, deferred execution, and IQueryable vs IEnumerable."),
            MissingSkill(skill="MVC", importance="medium", whyItMatters="The JD lists MVC and may ask about request flow and controller responsibilities.", howToPrepare="Revise routing, controllers, views, model binding, filters, and middleware differences."),
            MissingSkill(skill="Code compliance", importance="medium", whyItMatters="Enterprise projects care about maintainability, standards, and review practices.", howToPrepare="Prepare examples around code reviews, static analysis, naming, exception handling, logging, and secure coding."),
            MissingSkill(skill="End-to-end ownership", importance="high", whyItMatters="The JD emphasizes ownership from ideation to deployment.", howToPrepare="Prepare one project story covering requirement, design, implementation, testing, deployment, and production issue handling."),
        ],
        resumeImprovements=[
            ResumeImprovement(currentIssue="Resume is responsibility-heavy and low on measurable impact.", suggestedBullet="Built and maintained ASP.NET Core Web APIs for business workflows, improving reliability of API integrations and reducing manual support effort.", reason="Impact-based bullets create stronger interview discussion points."),
            ResumeImprovement(currentIssue="Database work is mentioned too broadly.", suggestedBullet="Implemented SQL Server queries, stored procedures, and data validation logic for high-volume application modules.", reason="Specific database ownership helps match SQL-heavy .NET roles."),
            ResumeImprovement(currentIssue="Frontend work is vague.", suggestedBullet="Delivered React UI enhancements, form validations, and API integration changes for user-facing workflow screens.", reason="This proves fullstack exposure instead of only backend support."),
            ResumeImprovement(currentIssue="Production support is not framed as engineering value.", suggestedBullet="Resolved production defects by debugging API logs, SQL data issues, and integration failures in an Agile delivery environment.", reason="Support experience can become valuable if written as debugging and reliability work."),
            ResumeImprovement(currentIssue="Cloud and CI/CD evidence is missing.", suggestedBullet="Supported deployments through Azure DevOps pipelines and environment validation for .NET services.", reason="Only use this if true; it directly addresses JD expectations."),
        ],
        interviewQuestions=[
            InterviewQuestion(topic=".NET Core", question="Explain the request pipeline in ASP.NET Core.", difficulty="medium", expectedFocus="Middleware order, routing, controllers, dependency injection, filters, and response handling."),
            InterviewQuestion(topic="Web API", question="How do you design a clean REST API endpoint?", difficulty="medium", expectedFocus="Resources, HTTP methods, status codes, validation, pagination, and error response shape."),
            InterviewQuestion(topic="C#", question="What is the difference between interface and abstract class?", difficulty="easy", expectedFocus="Contract, shared implementation, multiple inheritance behavior, and use cases."),
            InterviewQuestion(topic="LINQ", question="What is deferred execution in LINQ?", difficulty="medium", expectedFocus="When queries execute, IEnumerable vs IQueryable, and performance implications."),
            InterviewQuestion(topic="Entity Framework", question="How do migrations work in Entity Framework Core?", difficulty="medium", expectedFocus="Model changes, migration files, database update, rollback, and production caution."),
            InterviewQuestion(topic="SQL", question="How would you optimize a slow SQL query?", difficulty="medium", expectedFocus="Execution plan, indexes, joins, filtering, select columns, and query statistics."),
            InterviewQuestion(topic="Frontend", question="How do you handle API integration from a frontend application?", difficulty="easy", expectedFocus="Loading, error state, validation, response mapping, and retry behavior."),
            InterviewQuestion(topic="Azure DevOps", question="What happens in a basic CI/CD pipeline?", difficulty="medium", expectedFocus="Build, test, artifact, release/deploy, approvals, and environment variables."),
        ],
        crossQuestions=[
            CrossQuestion(question="You mentioned ASP.NET Core APIs. Did you design any endpoint yourself or only modify existing ones?", whyAsked="Interviewers check real ownership depth.", expectedAnswerHint="Explain one endpoint from requirement to validation, service logic, database, and testing."),
            CrossQuestion(question="How did you handle authentication and authorization in your APIs?", whyAsked="Security is common in enterprise .NET roles.", expectedAnswerHint="Mention JWT/session, role checks, policies, middleware/filters, and secure defaults."),
            CrossQuestion(question="Where exactly did you use SQL Server in your project?", whyAsked="They want to separate real database work from basic CRUD exposure.", expectedAnswerHint="Discuss schema, joins, stored procedures, indexing, transactions, or debugging data issues."),
            CrossQuestion(question="Have you worked with Entity Framework or raw SQL?", whyAsked="JD requires EF and LINQ.", expectedAnswerHint="Be honest, then explain repository/data access patterns and what you have practiced."),
            CrossQuestion(question="What was your role in deployment or release activities?", whyAsked="JD expects Azure DevOps CI/CD exposure.", expectedAnswerHint="Explain build/release pipeline visibility, deployment validation, rollback awareness, and environment checks."),
            CrossQuestion(question="How do you debug production issues?", whyAsked="Production support is on the resume and can become a strong signal.", expectedAnswerHint="Discuss logs, repro steps, correlation IDs, SQL checks, API response tracing, and root cause analysis."),
            CrossQuestion(question="What is one feature you owned end-to-end?", whyAsked="The JD stresses ownership.", expectedAnswerHint="Use a STAR format: requirement, design, implementation, testing, release, result."),
            CrossQuestion(question="How would you make a .NET API scalable and maintainable?", whyAsked="Checks system design readiness for a 3-year developer.", expectedAnswerHint="Talk about layered architecture, async calls, caching, database indexes, logging, and horizontal scaling basics."),
        ],
        systemDesignReadiness=SystemDesignReadiness(
            level="moderate",
            reason="The candidate has API and database exposure but needs clearer examples of ownership, deployment, scaling, and reliability decisions.",
            topicsToPrepare=["Layered architecture", "API pagination", "Caching basics", "SQL indexing", "Authentication and authorization", "Logging and monitoring"],
        ),
        sevenDayPlan=_build_preparation_plan(request.preparationPlanDays),
        debug=DebugInfo(
            mode="mock",
            provider=provider,
            model=model,
            promptPreview=prompt[:1800],
            receivedExperienceYears=context.experienceYears,
            receivedTargetRole=context.targetRole,
            receivedCurrentStack=context.currentStack,
            scoreReason=_score_reason(context.experienceYears, score),
        ),
        scoreBreakdown=scoring.score_breakdown,
        shortlistingScore=scoring.shortlisting_score,
        interviewReadinessScore=scoring.interview_readiness_score,
        overallOpportunityScore=scoring.overall_opportunity_score,
        shortlistingFactors=scoring.shortlisting_factors,
        recommendedAction=scoring.recommended_action,
    )


def _attach_algorithmic_scoring(response: AnalysisResponse, request: AnalyzeRequest) -> None:
    scoring = score_resume_against_jd(request)
    response.technicalMatchScore = scoring.technical_match_score
    response.fitCategory = _fit_category(scoring.technical_match_score)
    response.scoreBreakdown = scoring.score_breakdown
    response.shortlistingScore = scoring.shortlisting_score
    response.interviewReadinessScore = scoring.interview_readiness_score
    response.overallOpportunityScore = scoring.overall_opportunity_score
    response.shortlistingFactors = scoring.shortlisting_factors
    response.recommendedAction = scoring.recommended_action


def _build_preparation_plan(days: int) -> list[DayPlan]:
    base_plan = [
        DayPlan(day=1, focus=".NET API story", tasks=["Prepare one end-to-end API feature explanation.", "Revise middleware, DI, routing, and filters."]),
        DayPlan(day=2, focus="SQL and LINQ", tasks=["Practice LINQ queries.", "Revise joins, indexes, grouping, and query optimization."]),
        DayPlan(day=3, focus="Entity Framework", tasks=["Build or revise a small EF Core CRUD module.", "Practice migrations and relationship mapping."]),
        DayPlan(day=4, focus="Azure and CI/CD", tasks=["Learn a basic Azure DevOps build-release flow.", "Prepare deployment-related interview answers."]),
        DayPlan(day=5, focus="Frontend integration", tasks=["Prepare React or Angular API integration examples.", "Revise loading, error, and validation states."]),
        DayPlan(day=6, focus="System design basics", tasks=["Design a job application tracker API.", "Cover schema, APIs, pagination, auth, and caching."]),
        DayPlan(day=7, focus="Mock interview", tasks=["Answer all cross-questions aloud.", "Rewrite resume bullets based on this analysis."]),
    ]
    extended_topics = [
        ("Production debugging", ["Practice explaining logs, correlation IDs, SQL checks, and root cause analysis."]),
        ("Authentication and authorization", ["Revise JWT flow, role checks, policies, middleware, and secure API defaults."]),
        ("Project ownership story", ["Prepare STAR-format answers for requirement, implementation, testing, release, and impact."]),
        ("Database depth", ["Practice transactions, indexes, execution plans, and stored procedure tradeoffs."]),
        ("Cloud basics", ["Revise App Service, Azure SQL, Key Vault, monitoring, and environment variables."]),
        ("Behavioral and HR screen", ["Prepare notice period, role switch reason, salary expectation, and project explanation answers."]),
        ("Final revision", ["Revisit weak topics, retake mock questions, and refine concise interview answers."]),
    ]

    plan = base_plan[: min(days, len(base_plan))]
    next_day = len(plan) + 1
    while len(plan) < days:
        focus, tasks = extended_topics[(next_day - len(base_plan) - 1) % len(extended_topics)]
        plan.append(DayPlan(day=next_day, focus=focus, tasks=tasks))
        next_day += 1
    return [item.model_copy(update={"day": index + 1}) for index, item in enumerate(plan)]


def _ensure_plan_length(response: AnalysisResponse, days: int) -> None:
    if len(response.sevenDayPlan) == days:
        return
    if len(response.sevenDayPlan) > days:
        response.sevenDayPlan = [
            item.model_copy(update={"day": index + 1})
            for index, item in enumerate(response.sevenDayPlan[:days])
        ]
        return

    generated_plan = _build_preparation_plan(days)
    existing = [
        item.model_copy(update={"day": index + 1})
        for index, item in enumerate(response.sevenDayPlan)
    ]
    response.sevenDayPlan = existing + generated_plan[len(existing) :]


def _resolve_llm_options(request: AnalyzeRequest) -> tuple[str, str, str]:
    settings = get_settings()
    if request.llmOptions:
        return request.llmOptions.mode, request.llmOptions.provider, request.llmOptions.model
    return settings.llm_mode, settings.llm_provider, settings.llm_model


def _calculate_mock_score(request: AnalyzeRequest) -> int:
    context = request.candidateContext
    resume_and_stack = f"{request.resumeText} {' '.join(context.currentStack)}".lower()
    jd_text = request.jobDescriptionText.lower()

    score = 34
    score += min(context.experienceYears * 7, 28)

    keyword_weights = {
        ".net": 5,
        "asp.net": 5,
        "web api": 5,
        "sql": 5,
        "react": 4,
        "azure": 4,
        "entity framework": 4,
        "linq": 3,
        "ci/cd": 3,
    }

    for keyword, weight in keyword_weights.items():
        if keyword in resume_and_stack:
            score += weight
        elif keyword in jd_text:
            score += 1

    return max(0, min(score, 100))


def _fit_category(score: int) -> str:
    if score >= 85:
        return "Strong Fit"
    if score >= 70:
        return "Good Fit"
    if score >= 50:
        return "Partial Fit"
    return "Weak Fit"


def _score_reason(experience_years: int, score: int) -> str:
    return (
        f"Score is calculated by the explainable scoring engine using experience-wise weights, "
        f"skill overlap, role relevance, database/backend depth, cloud/devops evidence, system design "
        f"signals, and shortlisting constraints. Experience supplied: {experience_years} year(s). "
        f"Current technical score: {score}."
    )
