from app.models.analysis import AnalyzeRequest


def build_analysis_prompt(request: AnalyzeRequest, include_preparation: bool = False) -> str:
    if include_preparation:
        return build_full_analysis_prompt(request)
    return build_score_analysis_prompt(request)


def build_score_analysis_prompt(request: AnalyzeRequest) -> str:
    context = request.candidateContext
    stack = ", ".join(context.currentStack)
    return f"""
You are a senior technical interviewer.

Task: produce only the resume-to-JD scoring evidence needed by the app. Do not generate preparation plans, resume rewrite advice, interview questions, or cross-question chains in this call.

Candidate profile:
- Target role: {context.targetRole}
- Experience: {context.experienceYears} years
- Current stack: {stack}
- Target market: {context.targetMarket}

Important instructions:
- Use the Resume as the primary evidence source.
- Use Candidate Context only to clarify background.
- Score technical fit only; do not consider notice period, location, salary, or joining availability.
- Keep coaching artifacts empty because they are generated by separate optional endpoints.
- Return only valid JSON.
- Do not include markdown.

Resume:
{request.resumeText}

Job Description:
{request.jobDescriptionText}

Return JSON using this exact structure:

{{
  "technicalMatchScore": number,
  "overallSummary": string,
  "fitCategory": "Strong Fit" | "Good Fit" | "Partial Fit" | "Weak Fit",
  "matchingSkills": [
    {{
      "skill": string,
      "evidenceFromResume": string,
      "jdRequirement": string
    }}
  ],
  "weaklyEvidencedSkills": [
    {{
      "skill": string,
      "source": string,
      "whyWeak": string,
      "howToStrengthenResume": string
    }}
  ],
  "missingSkills": [
    {{
      "skill": string,
      "importance": "high" | "medium" | "low",
      "whyItMatters": string,
      "howToPrepare": string
    }}
  ],
  "resumeImprovements": [],
  "interviewQuestions": [],
  "crossQuestions": [],
  "systemDesignReadiness": {{
    "level": "strong" | "moderate" | "weak",
    "reason": string,
    "topicsToPrepare": [string]
  }},
  "sevenDayPlan": []
}}

Rules:
- technicalMatchScore must be between 0 and 100.
- technicalMatchScore should be based mainly on Resume evidence against the JD.
- Give matchingSkills, weaklyEvidencedSkills, and missingSkills only as evidence for scoring.
- resumeImprovements, interviewQuestions, crossQuestions, and sevenDayPlan must be empty arrays.
- Keep the answer realistic for the candidate's experience level.
""".strip()


def build_full_analysis_prompt(request: AnalyzeRequest) -> str:
    context = request.candidateContext
    stack = ", ".join(context.currentStack)
    return f"""
You are a senior technical interviewer and career coach.

Task: produce a legacy full analysis. Prefer separate endpoints for production use; this prompt is kept only for compatibility.

Candidate profile:
- Target role: {context.targetRole}
- Experience: {context.experienceYears} years
- Current stack: {stack}
- Target market: {context.targetMarket}
- Preparation plan length: {request.preparationPlanDays} days

Important instructions:
- Use the Resume as the primary evidence source.
- Use Candidate Context only to clarify background.
- Score technical fit only; do not consider notice period, location, salary, or joining availability.
- Return only valid JSON.
- Do not include markdown.

Resume:
{request.resumeText}

Job Description:
{request.jobDescriptionText}

Return JSON using this exact structure:

{{
  "technicalMatchScore": number,
  "overallSummary": string,
  "fitCategory": "Strong Fit" | "Good Fit" | "Partial Fit" | "Weak Fit",
  "matchingSkills": [
    {{
      "skill": string,
      "evidenceFromResume": string,
      "jdRequirement": string
    }}
  ],
  "weaklyEvidencedSkills": [
    {{
      "skill": string,
      "source": string,
      "whyWeak": string,
      "howToStrengthenResume": string
    }}
  ],
  "missingSkills": [
    {{
      "skill": string,
      "importance": "high" | "medium" | "low",
      "whyItMatters": string,
      "howToPrepare": string
    }}
  ],
  "resumeImprovements": [
    {{
      "currentIssue": string,
      "suggestedBullet": string,
      "reason": string
    }}
  ],
  "interviewQuestions": [
    {{
      "topic": string,
      "question": string,
      "difficulty": "easy" | "medium" | "hard",
      "expectedFocus": string
    }}
  ],
  "crossQuestions": [
    {{
      "question": string,
      "whyAsked": string,
      "expectedAnswerHint": string
    }}
  ],
  "systemDesignReadiness": {{
    "level": "strong" | "moderate" | "weak",
    "reason": string,
    "topicsToPrepare": [string]
  }},
  "sevenDayPlan": [
    {{
      "day": number,
      "focus": string,
      "tasks": [string]
    }}
  ]
}}

Rules:
- technicalMatchScore must be between 0 and 100.
- sevenDayPlan must contain exactly {request.preparationPlanDays} day(s).
- day must start at 1 and end at {request.preparationPlanDays}.
- Keep the answer realistic for the candidate's experience level.
""".strip()
